config = {
    'action': {'type': 'ContinuousAction'},
    'add_walls': True,
    'centering_position': [0.5, 0.5],
    'collision_reward': -5,
    'controlled_vehicles': 1,
    'duration': 100,
    'manual_control': False,
    'observation': {'features': ['x', 'y', 'vx', 'vy', 'cos_h', 'sin_h'],
                    'normalize': False,
                    'scales': [100, 100, 5, 5, 1, 1],
                    'type': 'KinematicsGoal'},
    'offscreen_rendering': False,
    'other_vehicles_type': 'highway_env.vehicle.behavior.IDMVehicle',
    'policy_frequency': 5,
    'real_time_rendering': False,
    'render_agent': True,
    'reward_weights': [1, 0.3, 0, 0, 0.02, 0.02],
    'scaling': 7,
    'screen_height': 300,
    'screen_width': 600,
    'show_trajectories': False,
    'simulation_frequency': 15,
    'steering_range': 0.7853981633974483,
    'success_goal_reward': 0.12,
    'vehicles_count': 0,
}
